// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
// PROJECTS
export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
export const GET_PROJECTS = "GET_PROJECTS";
export const LOAD_PROJECTS_FAIL = "LOAD_PROJECTS_FAIL";
export const GET_SINGLE_PROJECT = "GET_SINGLE_PROJECT";
export const ERROR_SINGLE_PROJECT = "ERROR_SINGLE_PROJECT";
export const PROJECT_LOADING = "PROJECT_LOADING";
export const LEAVE_PROJECT = "LEAVE_PROJECT";
export const UPDATE_PROJECT_STATUS = "UPDATE_PROJECT_STATUS";
export const UPDATE_PROJECT_STATUS_FAIL = "UPDATE_PROJECT_STATUS_FAIL";
// MODAL
export const SHOW_TASK_MODAL = "SHOW_TASK_MODAL";
export const CLOSE_TASK_MODAL = "CLOSE_TASK_MODAL";
// MEMBERS
export const GET_MEMBERS = "GET_MEMBERS";
export const GET_MEMBERS_FAIL = "GET_MEMBERS_FAIL";
export const UPDATE_MEMBER_ROLE = "UPDATE_MEMBER_ROLE";
export const DELETE_MEMBER = "DELETE_MEMBER";
// SECTIONS
export const CREATE_SECTION = "CREATE_SECTION";
export const CREATE_SECTION_FAIL = "CREATE_SECTION_FAIL";
export const GET_SECTIONS = "GET_SECTIONS";
export const GET_SECTIONS_FAIL = "GET_SECTIONS_FAIL";
export const DELETE_SECTION = "DELETE_SECTION";
export const DELETE_SECTION_FAIL = "DELETE_SECTION_FAIL";
export const RESET_SECTIONS = "RESET_SECTIONS";
export const GET_MODAL_SECTIONS = "GET_MODAL_SECTIONS";
export const GET_MODAL_SECTIONS_FAIL = "GET_MODAL_SECTIONS_FAIL";
// TASKS
export const CREATE_TASK = "CREATE_TASK";
export const GET_ASSIGNEES = "GET_ASSIGNEES";
export const GET_ASSIGNEES_FAIL = "GET_ASSIGNEES_FAIL";
export const UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS";
export const UPDATE_TASK_PRIORITY = "UPDATE_TASK_PRIORITY";
export const UPDATE_TASK_START = "UPDATE_TASK_START";
export const UPDATE_TASK_START_FAIL = "UPDATE_TASK_START_FAIL";
export const UPDATE_TASK_END = "UPDATE_TASK_END";
export const UPDATE_TASK_END_FAIL = "UPDATE_TASK_END_FAIL";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_PROJECT_TASKS_FAIL = "GET_PROJECT_TASKS_FAIL";
export const TASKS_LOADING = "TASKS_LOADING";
export const GET_PERSONAL_TASKS = "GET_PERSONAL_TASKS";
export const GET_PERSONAL_TASKS_FAIL = "GET_PERSONAL_TASK_FAIL";
export const SECTIONS_LOADING = "SECTIONS_LOADING";
// INVITATION
export const CREATE_INVITATION = "CREATE_INVITATION";
export const CREATE_INVITATION_FAIL = "CREATE_INVITATION_FAIL";
export const GET_INVITATIONS = "GET_INVITATIONS";
export const GET_PROJECT_INVITATIONS = "GET_PROJECT_INVITATIONS";
export const GET_INVITATIONS_FAIL = "GET_INVITATIONS_FAIL";
export const UPDATE_SEEN_INVITATION = "UPDATE_SEEN_INVITATION";
// FAVORITE PROJECTS
export const SET_FAVORITE_PROJECT = "SET_FAVORITE_PROJECT";
export const SET_FAVORITE_PROJECT_FAIL = "SET_FAVORITE_PROJECT_FAIL";
// PROJECT POSTS
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";
// COLORS
export const UPDATE_PROJECT_COLOR = "UPDATE_PROJECT_COLOR";
// SESSIONS
export const CREATE_SESSION = "CREATE_SESSION";
export const CREATE_SESSION_FAIL = "CREATE_SESSION_FAIL";
export const GET_SESSIONS = "GET_SESSIONS";
export const GET_SESSIONS_FAIL = "GET_SESSIONS_FAIL";
export const GET_SESSION = "GET_SESSION";
export const GET_SESSION_FAIL = "GET_SESSION_FAIL";
export const SESSIONS_LOADING = "SECTIONS_LOADING";

export const DATA_LOADING = "DATA_LOADING";

export const CREATE_TALKING_POINT = "CREATE_TALKING_POINT";
export const CREATE_TALKING_POINT_FAIL = "CREATE_TALKING_POINT_FAIL";
export const GET_TALKING_POINTS = "GET_TALKING_POINTS";
export const GET_TALKING_POINTS_FAIL = "GET_TALKING_POINTS_FAIL";
export const UPDATE_CHECK_STATUS = "UPDATE_CHECK_STATUS";

export const GET_FILES = "GET_FILES";

export const CREATE_FOLDER = "CREATE_FOLDER";
export const CREATE_FOLDER_FAIL = "CREATE_FOLDER_FAIL";
export const GET_FOLDERS = "GET_FOLDERS";
export const GET_FOLDERS_FAIL = "GET_FOLDERS_FAIL";

export const CREATE_TIME_RECORD = "CREATE_TIME_RECORD";
export const CREATE_TIME_RECORD_FAIL = "CREATE_TIME_RECORD_FAIL";
export const GET_TIME_RECORDS = "GET_TIME_RECORDS";
export const GET_TIME_RECORDS_FAIL = "GET_TIME_RECORDS_FAIL";
